---
- name: Evaluate {{ operators_project }} namespace if not exists
  k8s:
    api_version: v1
    kind: Namespace
    name: '{{ operators_project }}'
    state: present
  when:
    - operators_project is defined
    - operators_project | trim() != "openshift-operators"       

- name: Evaluate Operator Group
  k8s:
    api_version: operators.coreos.com/v1alpha2
    kind: OperatorGroup
    name: workshop-operators
    namespace: '{{ operators_project }}'
  when:
    - operators_project is defined
    - operators_project | trim() != "openshift-operators"   

- name: Evaluate Camel K Subscription
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'camelk-subscription.yaml.j2') }}"

- name: "Wait until InstallPlan is available"
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    namespace: "{{ operators_project }}"
    name: red-hat-camel-k
  register: sub
  retries: 30
  delay: 10
  until:
   - sub.resources[0].status.installplan.name is defined

- name: Approve InstallPlan
  shell: 
    cmd: >
      oc patch installplan {{ sub.resources[0].status.installplan.name }} -n {{ operators_project }}  --type=json -p='[{"op": "replace", "path": "/spec/approved", "value": true}]'

- name: "Wait for Camel K operator to be ready"
  k8s_info:
    api_version: v1
    kind: Deployment
    namespace: '{{ operators_project }}'
    name: "camel-k-operator"
  register: camel_k_operator_deployment
  retries: 20
  delay: 10
  until:
    - camel_k_operator_deployment.resources is defined
    - camel_k_operator_deployment.resources | length | int > 0
    - camel_k_operator_deployment.resources[0].status.availableReplicas is defined
    - camel_k_operator_deployment.resources[0].status.availableReplicas | int == camel_k_operator_deployment.resources[0].spec.replicas | int
